name = "SimT2D"
uuid = "a3ae81af-56a3-442d-870f-4d537fedbc5a"
authors = ["Tanja Bugajski <Tbugaj17> and Eduardo Vera-Valdés <everval>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
DataFrames = "1.8.0"
Distributions = "0.25.120"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
